require 'rake'
require 'rspec/core/rake_task'

task :spec    => 'spec:all'
task :default => :spec

namespace :spec do
  task :all     => :spec
  task :default => :all

  RSpec::Core::RakeTask.new(:spec) do |t|
    t.pattern = 'spec/*_spec.rb'
  end

  if ENV['GENERATE_XML_REPORTS']
    require 'ci/reporter/rake/rspec'
    task :spec => 'ci:setup:rspec'
  end
end
